INSERT INTO PUBLIC.FILMS_RATINGS (RATING_ID, RATING_NAME)
VALUES (1, 'G');

INSERT INTO PUBLIC.FILMS_RATINGS (RATING_ID, RATING_NAME)
VALUES (2, 'PG');

INSERT INTO PUBLIC.FILMS_RATINGS (RATING_ID, RATING_NAME)
VALUES (3, 'PG-13');

INSERT INTO PUBLIC.FILMS_RATINGS (RATING_ID, RATING_NAME)
VALUES (4, 'R');

INSERT INTO PUBLIC.FILMS_RATINGS (RATING_ID, RATING_NAME)
VALUES (5, 'NC-17');



INSERT INTO PUBLIC.GENRES (GENRE_ID, GENRE_NAME)
VALUES (1, 'Комедия');

INSERT INTO PUBLIC.GENRES (GENRE_ID, GENRE_NAME)
VALUES (2, 'Драма');

INSERT INTO PUBLIC.GENRES (GENRE_ID, GENRE_NAME)
VALUES (3, 'Мультфильм');

INSERT INTO PUBLIC.GENRES (GENRE_ID, GENRE_NAME)
VALUES (4, 'Триллер');

INSERT INTO PUBLIC.GENRES (GENRE_ID, GENRE_NAME)
VALUES (5, 'Документальный');

INSERT INTO PUBLIC.GENRES (GENRE_ID, GENRE_NAME)
VALUES (6, 'Боевик');